trades:
  item_example:
    maxuses: 1
    result:
      type: item
      amount: 1
      material: GOLDEN_HELMET
      custommodeldata: 1001 # optional
      name: "Golden Crown" # optional
      lore: # optional
        - "Only for the worthy"
        - "Hail to the king, baby"
      enchants: # optional
        - DURABILITY:2
    ingridient1:
      type: item
      amount: 1
      material: EMERALD
      custommodeldata: 1001 # optional
      enchants: # optional
        - DURABILITY:1
    ingridient2:
      type: none
  head_example:
    maxuses: 1
    result:
      type: head
      head: YouHaveTrouble
      amount: 1
      name: "YouHaveTrouble's Head"
      lore:
        - "You're free to hit it"
        - "if I do something stupid"
      enchants:
        - DURABILITY:10
    ingridient1:
      type: item
      material: EMERALD
      amount: 1
      name: "Cool Emerald" #optional
      lore: # optional
        - "Emerald, but cooler"
    ingridient2:
      type: item
      material: EMERALD
      amount: 1
